### ISSUE TITLE
[Proposition] renommer le champ "Echéances" en "Evénements / Echéances"

### ISSUE THREAD

**Issue by Eric-Hei** [SocialGouv/carnets#23]
Suggestion faite par Virginie

**Comment by gary-van-woerkens** [comment]
Etant donné que cela force à gérer des cas particuliers pour certains labels, la proposition est rejetée.
Si on trouve quelque chose de parlant et dont la taille correspond aux autres labels, je referai un test.

**Wrap**:
<img width="529" alt="Screenshot 2020-01-31 at 14 12 31" src="https://user-images.githubusercontent.com/59922165/73542005-10db0a00-4434-11ea-9f64-8ec7f1c8b926.png">

**No wrap**:
<img width="536" alt="Screenshot 2020-01-31 at 14 12 47" src="https://user-images.githubusercontent.com/59922165/73542035-1f292600-4434-11ea-9d2d-e19e63b9b8dc.png">

**Comment by gary-van-woerkens** [comment]
Du à un changement dans l'interface, il est maintenant possible d'effectuer ce changement.

**Comment by gary-van-woerkens** [comment]
Done.
