### ISSUE TITLE
ETQ utilisateur, je veux pouvoir modifier une saisie que j'ai effectuée

### ISSUE THREAD

**Issue by Eric-Hei** [SocialGouv/carnets#31]
Une fois publiée on ne peux pas corriger une faute de frappe/orthographe (voire plus si affinité ;)).
Donner la possibilité à un utilisateur d'éditer le texte d'un post. Pas de notion de droit/"c'est moi qui l'ai créé, c'est moi qui modifie", tout le monde peux éditer un post.

**Comment by revolunet** [comment]
en attendant, ca peut toujours se faire via une PR github vu que le contenu est posté en tant que fichier...

**Comment by gary-van-woerkens** [comment]
Ca me parait être une bonne idée ;)
En attendant, tu peux aussi refaire une publication et demander la suppression des publications erronées.
N'apparait sur la premiere page que la dernière publication de chaque team et il en sera de meme dans le standup.
